name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: short commt id
        shell: bash
        run: |
            echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: shadab781/python-app:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' ./charts/templates/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml tag to ${{ needs.ci.outputs.commit_id }}"

      - name: Ensure ArgoCD CLI is installed
        shell: bash
        run: |
          if ! command -v argocd &> /dev/null; then
            echo "ArgoCD CLI not found. Installing..."
            sudo curl -ksSL -o /usr/local/bin/argocd https://argocd-server.argocd/download/argocd-linux-amd64
            sudo chmod +x /usr/local/bin/argocd
          else
            echo "ArgoCD CLI is already installed!"
          fi

      - name: Argocd Sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password "${{ secrets.ARGOCD_PASSWORD }}"
          argocd app sync python-app